name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libcunit1 libcunit1-doc libcunit1-dev clang-format

    - name: Lint code with clang-format
      run: |

    - name: Compile code
      run: |
        g++ -Wall -Wextra src/main.cpp -o src/output/main
        g++ -Wall -Wextra src/test.cpp -o src/output/test -lcunit

    - name: Run code
      run: src/output/main

    - name: Run tests
      run: src/output/test
